version: "3.7"

services:
  backend:
    build: ./backend

    volumes:
    - ./backend:/app/backend

    ports:
      - 8000:8000
    stdin_open: true
    depends_on:
      - db
    command: gunicorn api_project.wsgi --bind 0.0.0.0:8000

  frontend:
    build: ./frontend

    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

    command: npm start

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
