version: '3.7'

services:
  backend:
    build: ./backend
    command: gunicorn api_project.wsgi -b 0.0.0.0:8000
    environment:
      - ENVIRONMENT=production
      - SECRET_KEY=hartopormil1234
      - DEBUG=0

    ports:
      - 8000:8000
    stdin_open: true
    depends_on:
      - db

  frontend:
    build: ./frontend

    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

    command: npm start

  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
