# Generated by Django 3.0.8 on 2020-07-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=546)),
                ('titulo', models.CharField(max_length=546)),
                ('url_pic', models.URLField(max_length=546, null=True)),
                ('year', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
