# Generated by Django 3.0.8 on 2020-07-02 00:24

from django.db import migrations


def create_data(apps, schema_editor):
    Picture = apps.get_model('api_app', 'Pictures')
    Picture(autor="petite.doll",
            url_pic="https://pbs.twimg.com/media/Ebyb6sjXQAEMvWW?format=jpg&name=900x900",
            titulo="Coffewoman",
            year="2020").save()


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
