# Generated by Django 3.0.8 on 2020-07-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_pictures'),
        ('api_app', '0003_pics'),
    ]

    operations = [
    ]
